export const PlatformError = {
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  PROFILE_CREATE_FAILED: 'PROFILE_CREATE_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  FETCH_FAILED: 'FETCH_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  APPLICATION_FAILED: 'APPLICATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type PlatformErrorCode = typeof PlatformError[keyof typeof PlatformError];

